[config]
exclude-merge-commits = true

[matchers]
conventional-commit = "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\(.+\\))?: .+$"

[examples]
conventional-commit = "feat: add new feature"

